# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc.face_rec_pb2 as face__rec__pb2


class FaceRecognitionStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.face_rec_str = channel.unary_unary(
        '/face_rec_rpc.FaceRecognition/face_rec_str',
        request_serializer=face__rec__pb2.MyStr.SerializeToString,
        response_deserializer=face__rec__pb2.Image.FromString,
        )


class FaceRecognitionServicer(object):
  """The greeting service definition.
  """

  def face_rec_str(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'face_rec_str': grpc.unary_unary_rpc_method_handler(
          servicer.face_rec_str,
          request_deserializer=face__rec__pb2.MyStr.FromString,
          response_serializer=face__rec__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'face_rec_rpc.FaceRecognition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
