# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_rec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_rec.proto',
  package='face_rec_rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66\x61\x63\x65_rec.proto\x12\x0c\x66\x61\x63\x65_rec_rpc\"A\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x0e\n\x06stream\x18\x04 \x01(\t\"\x15\n\x05MyStr\x12\x0c\n\x04name\x18\x01 \x01(\t2M\n\x0f\x46\x61\x63\x65Recognition\x12:\n\x0c\x66\x61\x63\x65_rec_str\x12\x13.face_rec_rpc.MyStr\x1a\x13.face_rec_rpc.Image\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='face_rec_rpc.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='face_rec_rpc.Image.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='face_rec_rpc.Image.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='face_rec_rpc.Image.format', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream', full_name='face_rec_rpc.Image.stream', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=97,
)


_MYSTR = _descriptor.Descriptor(
  name='MyStr',
  full_name='face_rec_rpc.MyStr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='face_rec_rpc.MyStr.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['MyStr'] = _MYSTR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:face_rec_rpc.Image)
  ))
_sym_db.RegisterMessage(Image)

MyStr = _reflection.GeneratedProtocolMessageType('MyStr', (_message.Message,), dict(
  DESCRIPTOR = _MYSTR,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:face_rec_rpc.MyStr)
  ))
_sym_db.RegisterMessage(MyStr)



_FACERECOGNITION = _descriptor.ServiceDescriptor(
  name='FaceRecognition',
  full_name='face_rec_rpc.FaceRecognition',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=122,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='face_rec_str',
    full_name='face_rec_rpc.FaceRecognition.face_rec_str',
    index=0,
    containing_service=None,
    input_type=_MYSTR,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACERECOGNITION)

DESCRIPTOR.services_by_name['FaceRecognition'] = _FACERECOGNITION

# @@protoc_insertion_point(module_scope)
